Updated sugargame and miscellaneous fixes
sugarlabs/flappy-birds-activity pull request #13
Opened 2018-02-10 10:38 UTC by yashagrawal3

- added .gitignore
- removed score.pkl
- fix fail to start
- updated sugargame

@quozl please review!

2018-02-12 00:40 UTC, quozl requested changes
Thanks, looks good, a few changes requested;

2018-02-12 00:40 UTC, quozl commented on activity.py
Remove these lines rather than comment them.

2018-02-12 00:40 UTC, quozl commented on activity.py
> +        self.game.canvas = sugargame.canvas.PygameCanvas(self, main=self.game.make, modules=[pygame.display, pygame.font])
Wrap line; use flake8 to verify.

2018-02-13 18:49 UTC, yashagrawal3 commented
@quozl Done both as suggested.

2018-02-13 22:03 UTC, merged